// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type About struct {
	ID        int64            `json:"id"`
	UserID    int64            `json:"user_id"`
	Bio       string           `json:"bio"`
	Company   string           `json:"company"`
	Readme    string           `json:"readme"`
	JobTitle  string           `json:"job_title"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type MagicLink struct {
	Email     string           `json:"email"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	Token     string           `json:"token"`
}

type SocialLink struct {
	ID            int64            `json:"id"`
	UserID        int64            `json:"user_id"`
	Github        string           `json:"github"`
	Linkedin      string           `json:"linkedin"`
	Website       string           `json:"website"`
	X             string           `json:"x"`
	Youtube       string           `json:"youtube"`
	StackOverflow string           `json:"stack_overflow"`
	Reddit        string           `json:"reddit"`
	RoadmapSh     string           `json:"roadmap_sh"`
	Codepen       string           `json:"codepen"`
	Mastodon      string           `json:"mastodon"`
	Threads       string           `json:"threads"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
}

type Streak struct {
	ID            int64            `json:"id"`
	UserID        int64            `json:"user_id"`
	StreakStart   pgtype.Timestamp `json:"streak_start"`
	StreakEnd     pgtype.Timestamp `json:"streak_end"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
	StreakLength  int32            `json:"streak_length"`
	LongestStreak int32            `json:"longest_streak"`
}

type User struct {
	ID           int64            `json:"id"`
	Name         string           `json:"name"`
	Username     string           `json:"username"`
	Avatar       pgtype.Text      `json:"avatar"`
	Email        string           `json:"email"`
	Profession   pgtype.Text      `json:"profession"`
	UserPassword pgtype.Text      `json:"user_password"`
	RefreshToken pgtype.Text      `json:"refresh_token"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	IsVerified   bool             `json:"is_verified"`
}

type UserStat struct {
	ID         int64 `json:"id"`
	UserID     int64 `json:"user_id"`
	Followers  int32 `json:"followers"`
	Following  int32 `json:"following"`
	Reputation int32 `json:"reputation"`
	Views      int32 `json:"views"`
	Upvotes    int32 `json:"upvotes"`
}
