// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAbout = `-- name: CreateAbout :one
INSERT INTO about (
  user_id,
  bio,
  company,
  job_title
)
VALUES (
  $1,
  '',
  '',
  ''
)
RETURNING id, user_id, bio, company, readme, job_title, created_at
`

func (q *Queries) CreateAbout(ctx context.Context, userID int64) (About, error) {
	row := q.db.QueryRow(ctx, createAbout, userID)
	var i About
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Bio,
		&i.Company,
		&i.Readme,
		&i.JobTitle,
		&i.CreatedAt,
	)
	return i, err
}

const createGithubSocialLink = `-- name: CreateGithubSocialLink :one
INSERT INTO social_links (
  user_id,
  github
)
VALUES (
  $1,
  $2
)
RETURNING id, user_id, github, linkedin, website, x, youtube, stack_overflow, reddit, roadmap_sh, codepen, mastodon, threads, created_at
`

type CreateGithubSocialLinkParams struct {
	UserID int64  `json:"user_id"`
	Github string `json:"github"`
}

func (q *Queries) CreateGithubSocialLink(ctx context.Context, arg CreateGithubSocialLinkParams) (SocialLink, error) {
	row := q.db.QueryRow(ctx, createGithubSocialLink, arg.UserID, arg.Github)
	var i SocialLink
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Github,
		&i.Linkedin,
		&i.Website,
		&i.X,
		&i.Youtube,
		&i.StackOverflow,
		&i.Reddit,
		&i.RoadmapSh,
		&i.Codepen,
		&i.Mastodon,
		&i.Threads,
		&i.CreatedAt,
	)
	return i, err
}

const createMagicLink = `-- name: CreateMagicLink :one
INSERT INTO magic_links (
  email,
  token
)
VALUES (
  $1,
  $2
)
RETURNING email, created_at, token
`

type CreateMagicLinkParams struct {
	Email string `json:"email"`
	Token string `json:"token"`
}

func (q *Queries) CreateMagicLink(ctx context.Context, arg CreateMagicLinkParams) (MagicLink, error) {
	row := q.db.QueryRow(ctx, createMagicLink, arg.Email, arg.Token)
	var i MagicLink
	err := row.Scan(&i.Email, &i.CreatedAt, &i.Token)
	return i, err
}

const createSocialLinks = `-- name: CreateSocialLinks :one
INSERT INTO social_links (
  user_id
)
VALUES (
  $1
)
RETURNING id, user_id, github, linkedin, website, x, youtube, stack_overflow, reddit, roadmap_sh, codepen, mastodon, threads, created_at
`

func (q *Queries) CreateSocialLinks(ctx context.Context, userID int64) (SocialLink, error) {
	row := q.db.QueryRow(ctx, createSocialLinks, userID)
	var i SocialLink
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Github,
		&i.Linkedin,
		&i.Website,
		&i.X,
		&i.Youtube,
		&i.StackOverflow,
		&i.Reddit,
		&i.RoadmapSh,
		&i.Codepen,
		&i.Mastodon,
		&i.Threads,
		&i.CreatedAt,
	)
	return i, err
}

const createStreak = `-- name: CreateStreak :one
INSERT INTO streaks (
  user_id
)
VALUES (
  $1
)
RETURNING id, user_id, streak_start, streak_end, updated_at, streak_length, longest_streak
`

func (q *Queries) CreateStreak(ctx context.Context, userID int64) (Streak, error) {
	row := q.db.QueryRow(ctx, createStreak, userID)
	var i Streak
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StreakStart,
		&i.StreakEnd,
		&i.UpdatedAt,
		&i.StreakLength,
		&i.LongestStreak,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  name,
  username,
  profession,
  email,
  user_password
)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5
)
RETURNING id, name, username, avatar, email, profession, user_password, refresh_token, created_at, is_verified
`

type CreateUserParams struct {
	Name         string      `json:"name"`
	Username     string      `json:"username"`
	Profession   pgtype.Text `json:"profession"`
	Email        string      `json:"email"`
	UserPassword pgtype.Text `json:"user_password"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Name,
		arg.Username,
		arg.Profession,
		arg.Email,
		arg.UserPassword,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.Avatar,
		&i.Email,
		&i.Profession,
		&i.UserPassword,
		&i.RefreshToken,
		&i.CreatedAt,
		&i.IsVerified,
	)
	return i, err
}

const createUserStats = `-- name: CreateUserStats :one
INSERT INTO user_stats (
  user_id,
  followers,
  following,
  reputation,
  views,
  upvotes
)
VALUES (
  $1,
  0,
  0,
  0,
  0,
  0
)
RETURNING id, user_id, followers, following, reputation, views, upvotes
`

func (q *Queries) CreateUserStats(ctx context.Context, userID int64) (UserStat, error) {
	row := q.db.QueryRow(ctx, createUserStats, userID)
	var i UserStat
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Followers,
		&i.Following,
		&i.Reputation,
		&i.Views,
		&i.Upvotes,
	)
	return i, err
}

const deleteMagicLinksByEmail = `-- name: DeleteMagicLinksByEmail :exec
DELETE FROM
  magic_links
WHERE
  email = $1
`

func (q *Queries) DeleteMagicLinksByEmail(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, deleteMagicLinksByEmail, email)
	return err
}

const findMagicLinkByToken = `-- name: FindMagicLinkByToken :one
SELECT
  email
FROM
  magic_links
WHERE
  token = $1
`

func (q *Queries) FindMagicLinkByToken(ctx context.Context, token string) (string, error) {
	row := q.db.QueryRow(ctx, findMagicLinkByToken, token)
	var email string
	err := row.Scan(&email)
	return email, err
}

const findUserByEmail = `-- name: FindUserByEmail :one
SELECT
  id, name, username, avatar, email, profession, user_password, refresh_token, created_at, is_verified
FROM
  users
WHERE
  email = $1
`

func (q *Queries) FindUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, findUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.Avatar,
		&i.Email,
		&i.Profession,
		&i.UserPassword,
		&i.RefreshToken,
		&i.CreatedAt,
		&i.IsVerified,
	)
	return i, err
}

const findUserByID = `-- name: FindUserByID :one
SELECT
  id, name, username, avatar, email, profession, user_password, refresh_token, created_at, is_verified
FROM
  users
WHERE
  id = $1
`

func (q *Queries) FindUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, findUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.Avatar,
		&i.Email,
		&i.Profession,
		&i.UserPassword,
		&i.RefreshToken,
		&i.CreatedAt,
		&i.IsVerified,
	)
	return i, err
}

const findUserEmail = `-- name: FindUserEmail :one
SELECT
  email
FROM
  users
WHERE
  email = $1
`

func (q *Queries) FindUserEmail(ctx context.Context, email string) (string, error) {
	row := q.db.QueryRow(ctx, findUserEmail, email)
	var email_2 string
	err := row.Scan(&email_2)
	return email_2, err
}

const findVerifiedUserByEmail = `-- name: FindVerifiedUserByEmail :one
SELECT
  id,
  name,
  username,
  avatar,
  email,
  user_password,
  profession
FROM
  users
WHERE
  email = $1
  AND is_verified = $2
`

type FindVerifiedUserByEmailParams struct {
	Email      string `json:"email"`
	IsVerified bool   `json:"is_verified"`
}

type FindVerifiedUserByEmailRow struct {
	ID           int64       `json:"id"`
	Name         string      `json:"name"`
	Username     string      `json:"username"`
	Avatar       pgtype.Text `json:"avatar"`
	Email        string      `json:"email"`
	UserPassword pgtype.Text `json:"user_password"`
	Profession   pgtype.Text `json:"profession"`
}

func (q *Queries) FindVerifiedUserByEmail(ctx context.Context, arg FindVerifiedUserByEmailParams) (FindVerifiedUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, findVerifiedUserByEmail, arg.Email, arg.IsVerified)
	var i FindVerifiedUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.Avatar,
		&i.Email,
		&i.UserPassword,
		&i.Profession,
	)
	return i, err
}

const updateRefreshToken = `-- name: UpdateRefreshToken :exec
UPDATE users
SET
  refresh_token = $1
WHERE
  email = $2
`

type UpdateRefreshTokenParams struct {
	RefreshToken pgtype.Text `json:"refresh_token"`
	Email        string      `json:"email"`
}

func (q *Queries) UpdateRefreshToken(ctx context.Context, arg UpdateRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, updateRefreshToken, arg.RefreshToken, arg.Email)
	return err
}

const verifyUserByEmail = `-- name: VerifyUserByEmail :one
UPDATE users
SET
  is_verified = $1
WHERE
  email = $2
RETURNING id, name, username, avatar, email, profession, user_password, refresh_token, created_at, is_verified
`

type VerifyUserByEmailParams struct {
	IsVerified bool   `json:"is_verified"`
	Email      string `json:"email"`
}

func (q *Queries) VerifyUserByEmail(ctx context.Context, arg VerifyUserByEmailParams) (User, error) {
	row := q.db.QueryRow(ctx, verifyUserByEmail, arg.IsVerified, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.Avatar,
		&i.Email,
		&i.Profession,
		&i.UserPassword,
		&i.RefreshToken,
		&i.CreatedAt,
		&i.IsVerified,
	)
	return i, err
}
