// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"context"
)

type Querier interface {
	CreateAbout(ctx context.Context, userID int64) (About, error)
	CreateGithubSocialLink(ctx context.Context, arg CreateGithubSocialLinkParams) (SocialLink, error)
	CreateMagicLink(ctx context.Context, arg CreateMagicLinkParams) (MagicLink, error)
	CreateSocialLinks(ctx context.Context, userID int64) (SocialLink, error)
	CreateStreak(ctx context.Context, userID int64) (Streak, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserStats(ctx context.Context, userID int64) (UserStat, error)
	DeleteMagicLinksByEmail(ctx context.Context, email string) error
	FindMagicLinkByToken(ctx context.Context, token string) (string, error)
	FindUserByEmail(ctx context.Context, email string) (User, error)
	FindUserByID(ctx context.Context, id int64) (User, error)
	FindUserEmail(ctx context.Context, email string) (string, error)
	FindVerifiedUserByEmail(ctx context.Context, arg FindVerifiedUserByEmailParams) (FindVerifiedUserByEmailRow, error)
	UpdateRefreshToken(ctx context.Context, arg UpdateRefreshTokenParams) error
	VerifyUserByEmail(ctx context.Context, arg VerifyUserByEmailParams) (User, error)
}

var _ Querier = (*Queries)(nil)
